version: '2'

services:
  ldrelay:
    image: launchdarkly/ld-relay
    environment:
      - LD_ENV_BENCHMARK=${LAUNCHDARKLY_SDK_KEY}
      - LD_MOBILE_KEY_BENCHMARK=${LAUNCHDARKLY_MOBILE_KEY}
      - USE_EVENTS=true
    ports:
      - "8030:8039"

  master:
    image: locust-ld-relay
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - LAUNCHDARKLY_SDK_KEY
      - LAUNCHDARKLY_MOBILE_KEY
      - LAUNCHDARKLY_HEARTBEAT_PROJECT
      - LAUNCHDARKLY_HEARTBEAT_API_KEY
      - TARGET_URL=http://ldrelay:8030
      - LAUNCHDARKLY_BASE_URI=http://ldrelay:8030
      - LAUNCHDARKLY_EVENTS_URI=http://ldrelay:8030
      - LAUNCHDARKLY_STREAM_URI=http://ldrelay:8030
      - LAUNCHDARKLY_MOBILE_STREAM_URI=http://ldrelay:8030
    depends_on:
      - ldrelay
    ports:
      - "8089:8089"
